# proposal generate
proposal_csv_path: '/home/dechao_meng/.action_proposals/results/pgm_proposals'
proposal_workers: 16

# feature generate
pgm_feature_path: '/home/dechao_meng/.action_proposals/results/pgm_features'
pgm_feature_workers: 16