# activitynet dataset
anet_dataset: !include activitynet_config.yml
pgm: !include pgm_config.yml

num_workers: 16

# model save and load
epochs: 20
save_root: '/home/dechao_meng/.action_proposals/models/tem'
continue_train: true

# train
input_features: 400
learning_rate: 1e-3
batch_size: 16
weight_decay: 2e-3

# test
tem_results_file: '/home/dechao_meng/.action_proposals/results/tem_results.pkl'

